version: '3.7'
services:
  sentry:
    image: sentry:9.0.0
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./sentry-config.yml:/etc/sentry/config.yml
    environment:
      - SENTRY_SECRET_KEY="%**stxva=es(qsts1z1eu!1uks3r9q8z@w8dh8hm&akv3p9a*s"
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry

  cron:
    image: sentry:9.0.0
    restart: unless-stopped
    environment:
      - SENTRY_SECRET_KEY="%**stxva=es(qsts1z1eu!1uks3r9q8z@w8dh8hm&akv3p9a*s"
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry
    command: run cron

  worker:
    image: sentry:9.0.0
    restart: unless-stopped
    environment:
      - SENTRY_SECRET_KEY="%**stxva=es(qsts1z1eu!1uks3r9q8z@w8dh8hm&akv3p9a*s"
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry
    command: run worker

  redis:
    image: redis:4.0-alpine
    restart: unless-stopped

  postgres:
    image: postgres:10.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sentry
      - POSTGRES_USER=sentry
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data


networks:
  default:
    name: sentry
