version: '3.4'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx:
    environment:
      - VIRTUAL_HOST=local.sentry.fr
      - VIRTUAL_PORT=9000

  wait_postgres:
    image: "index.docker.io/waisbrot/wait"
    environment:
      TARGETS: postgres:5432
